// Code generated by the multiversx-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           15
// Async Callback (empty):               1
// Total number of exported functions:  17

#![no_std]

// Configuration that works with rustc < 1.73.0.
// TODO: Recommended rustc version: 1.73.0 or newer.
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    coindrip
    (
        init => init
        getStreamData => get_stream
        getLastStreamId => last_stream_id
        getProtocolFee => protocol_fee
        createStreamDuration => create_stream_duration
        createStream => create_stream
        recipientBalance => recipient_balance
        senderBalance => sender_balance
        claimFromStream => claim_from_stream
        claimFromStreamMultiple => claim_from_stream_multiple
        cancelStream => cancel_stream
        claimFromStreamAfterCancel => claim_from_stream_after_cancel
        renounceCancelStream => renounce_cancel_stream
        setProtocolFee => set_protocol_fee
        removeProtocolFee => remove_protocol_fee
        getStatusOf => status_of
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
